/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_genius_smartappupdateslib_DiffUtils */

#ifndef _Included_com_genius_smartappupdateslib_DiffUtils
#define _Included_com_genius_smartappupdateslib_DiffUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_genius_smartappupdateslib_DiffUtils
 * Method:    genDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_genius_smartappupdateslib_DiffUtils_genDiff
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
