/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_genius_smartappupdateslib_PatchUtils */

#ifndef _Included_com_genius_smartappupdateslib_PatchUtils
#define _Included_com_genius_smartappupdateslib_PatchUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef com_genius_smartappupdateslib_PatchUtils_BUF_SIZE
#define com_genius_smartappupdateslib_PatchUtils_BUF_SIZE 8192L
/*
 * Class:     com_genius_smartappupdateslib_PatchUtils
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_genius_smartappupdateslib_PatchUtils_patch
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
